"""new table create

Revision ID: ad5fa672a0e4
Revises: 
Create Date: 2025-05-25 00:05:44.238305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5fa672a0e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesstypes',
    sa.Column('Business_Type_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Business_Type_Name', sa.String(length=100), nullable=False),
    sa.Column('Business_Type_Desc', sa.String(length=255), nullable=True),
    sa.Column('Business_Code', sa.String(length=100), nullable=True),
    sa.Column('Business_Status', sa.String(length=50), nullable=True),
    sa.Column('Is_Active', sa.CHAR(length=1), nullable=False),
    sa.Column('Business_Media', sa.String(length=500), nullable=True),
    sa.Column('Added_By', sa.Integer(), nullable=True),
    sa.Column('Added_On', sa.DateTime(), nullable=False),
    sa.Column('Modified_By', sa.Integer(), nullable=True),
    sa.Column('Modified_On', sa.DateTime(), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.Column('Deleted_On', sa.DateTime(), nullable=True),
    sa.Column('Is_Deleted', sa.CHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('Business_Type_Id')
    )
    op.create_index(op.f('ix_businesstypes_Business_Type_Id'), 'businesstypes', ['Business_Type_Id'], unique=False)
    op.create_index(op.f('ix_businesstypes_Business_Type_Name'), 'businesstypes', ['Business_Type_Name'], unique=True)
    op.create_table('locationmaster',
    sa.Column('Location_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Location_Name', sa.String(length=100), nullable=False),
    sa.Column('Location_City_Name', sa.String(length=100), nullable=False),
    sa.Column('Location_Dist_Name', sa.String(length=100), nullable=False),
    sa.Column('Location_State_Name', sa.String(length=100), nullable=False),
    sa.Column('Location_Country_Name', sa.String(length=100), nullable=False),
    sa.Column('Location_Desc', sa.String(length=255), nullable=True),
    sa.Column('Is_Active', sa.CHAR(length=1), nullable=False),
    sa.Column('Added_By', sa.Integer(), nullable=True),
    sa.Column('Added_On', sa.DateTime(), nullable=False),
    sa.Column('Modified_By', sa.Integer(), nullable=True),
    sa.Column('Modified_On', sa.DateTime(), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.Column('Deleted_On', sa.DateTime(), nullable=True),
    sa.Column('Is_Deleted', sa.CHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('Location_Id')
    )
    op.create_index(op.f('ix_locationmaster_Location_Id'), 'locationmaster', ['Location_Id'], unique=False)
    op.create_index(op.f('ix_locationmaster_Location_Name'), 'locationmaster', ['Location_Name'], unique=True)
    op.create_table('pages',
    sa.Column('Page_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Page_Name', sa.String(length=255), nullable=False),
    sa.Column('Page_Display_Text', sa.String(length=255), nullable=False),
    sa.Column('Page_Navigation_URL', sa.Text(), nullable=True),
    sa.Column('Page_Parent_Id', sa.Integer(), nullable=True),
    sa.Column('Is_Internal', sa.CHAR(length=1), nullable=False),
    sa.Column('Added_By', sa.Integer(), nullable=True),
    sa.Column('Added_On', sa.DateTime(), nullable=False),
    sa.Column('Modified_By', sa.Integer(), nullable=True),
    sa.Column('Modified_On', sa.DateTime(), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.Column('Deleted_On', sa.DateTime(), nullable=True),
    sa.Column('Is_Deleted', sa.CHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('Page_Id'),
    sa.UniqueConstraint('Page_Name')
    )
    op.create_index(op.f('ix_pages_Page_Id'), 'pages', ['Page_Id'], unique=False)
    op.create_table('usertypes',
    sa.Column('User_Type_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_Type_Name', sa.String(length=100), nullable=False),
    sa.Column('User_Type_Desc', sa.String(length=255), nullable=True),
    sa.Column('Default_Page', sa.String(length=255), nullable=True),
    sa.Column('Is_Member', sa.CHAR(length=1), nullable=False),
    sa.Column('Is_Active', sa.CHAR(length=1), nullable=False),
    sa.Column('Added_By', sa.Integer(), nullable=True),
    sa.Column('Added_On', sa.DateTime(), nullable=False),
    sa.Column('Modified_By', sa.Integer(), nullable=True),
    sa.Column('Modified_On', sa.DateTime(), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.Column('Deleted_On', sa.DateTime(), nullable=True),
    sa.Column('Is_Deleted', sa.CHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('User_Type_Id')
    )
    op.create_index(op.f('ix_usertypes_User_Type_Id'), 'usertypes', ['User_Type_Id'], unique=False)
    op.create_index(op.f('ix_usertypes_User_Type_Name'), 'usertypes', ['User_Type_Name'], unique=True)
    op.create_table('businesscategories',
    sa.Column('Business_Category_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Business_Type_Id', sa.Integer(), nullable=False),
    sa.Column('Business_Category_Name', sa.String(length=100), nullable=False),
    sa.Column('Business_Category_Short_Name', sa.String(length=300), nullable=False),
    sa.Column('Business_Category_Code', sa.String(length=100), nullable=True),
    sa.Column('Is_Active', sa.CHAR(length=1), nullable=False),
    sa.Column('Business_Category_Media', sa.String(length=500), nullable=True),
    sa.Column('Business_Category_Description', sa.String(length=500), nullable=True),
    sa.Column('Added_By', sa.Integer(), nullable=True),
    sa.Column('Added_On', sa.DateTime(), nullable=False),
    sa.Column('Modified_By', sa.Integer(), nullable=True),
    sa.Column('Modified_On', sa.DateTime(), nullable=False),
    sa.Column('Is_Deleted', sa.CHAR(length=1), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.Column('Deleted_On', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Business_Type_Id'], ['businesstypes.Business_Type_Id'], ),
    sa.PrimaryKeyConstraint('Business_Category_Id')
    )
    op.create_index(op.f('ix_businesscategories_Business_Category_Id'), 'businesscategories', ['Business_Category_Id'], unique=False)
    op.create_table('locationactivepincode',
    sa.Column('Pincode_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Pincode', sa.String(length=10), nullable=False),
    sa.Column('Location_Id', sa.Integer(), nullable=False),
    sa.Column('Location_Status', sa.String(length=10), nullable=False),
    sa.Column('Is_Active', sa.CHAR(length=1), nullable=False),
    sa.Column('Added_By', sa.Integer(), nullable=True),
    sa.Column('Added_On', sa.DateTime(), nullable=False),
    sa.Column('Modified_By', sa.Integer(), nullable=True),
    sa.Column('Modified_On', sa.DateTime(), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.Column('Deleted_On', sa.DateTime(), nullable=True),
    sa.Column('Is_Deleted', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['Location_Id'], ['locationmaster.Location_Id'], ),
    sa.PrimaryKeyConstraint('Pincode_Id')
    )
    op.create_index(op.f('ix_locationactivepincode_Pincode'), 'locationactivepincode', ['Pincode'], unique=True)
    op.create_index(op.f('ix_locationactivepincode_Pincode_Id'), 'locationactivepincode', ['Pincode_Id'], unique=False)
    op.create_table('userpermissions',
    sa.Column('User_Permission_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_Type_Id', sa.Integer(), nullable=False),
    sa.Column('Page_Id', sa.Integer(), nullable=False),
    sa.Column('Can_View', sa.CHAR(length=1), nullable=False),
    sa.Column('Can_Create', sa.CHAR(length=1), nullable=False),
    sa.Column('Can_Update', sa.CHAR(length=1), nullable=False),
    sa.Column('Can_Delete', sa.CHAR(length=1), nullable=False),
    sa.Column('Added_By', sa.Integer(), nullable=True),
    sa.Column('Added_On', sa.DateTime(), nullable=False),
    sa.Column('Modified_By', sa.Integer(), nullable=True),
    sa.Column('Modified_On', sa.DateTime(), nullable=False),
    sa.Column('Is_Deleted', sa.CHAR(length=1), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.Column('Deleted_On', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Page_Id'], ['pages.Page_Id'], ),
    sa.ForeignKeyConstraint(['User_Type_Id'], ['usertypes.User_Type_Id'], ),
    sa.PrimaryKeyConstraint('User_Permission_Id')
    )
    op.create_index(op.f('ix_userpermissions_User_Permission_Id'), 'userpermissions', ['User_Permission_Id'], unique=False)
    op.create_table('users',
    sa.Column('User_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Full_Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Phone', sa.String(length=15), nullable=True),
    sa.Column('Alt_Phone', sa.String(length=15), nullable=True),
    sa.Column('Password_Hash', sa.String(length=255), nullable=False),
    sa.Column('Forgot_Token', sa.String(length=255), nullable=True),
    sa.Column('Forgot_Token_Expiry', sa.DateTime(), nullable=True),
    sa.Column('User_Type_Id', sa.Integer(), nullable=True),
    sa.Column('Profile_Image', sa.String(length=255), nullable=True),
    sa.Column('Background_Image', sa.String(length=255), nullable=True),
    sa.Column('Bio', sa.Text(), nullable=True),
    sa.Column('Website', sa.String(length=255), nullable=True),
    sa.Column('Social_Links', sa.Text(), nullable=True),
    sa.Column('Gender', sa.String(length=10), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('Occupation', sa.String(length=100), nullable=True),
    sa.Column('Company_Name', sa.String(length=100), nullable=True),
    sa.Column('GST_Number', sa.String(length=50), nullable=True),
    sa.Column('Referral_Code', sa.String(length=50), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('State', sa.String(length=100), nullable=True),
    sa.Column('Country', sa.String(length=100), nullable=True),
    sa.Column('Postal_Code', sa.String(length=20), nullable=True),
    sa.Column('Preferred_Language', sa.String(length=10), nullable=True),
    sa.Column('Is_Verified', sa.Boolean(), nullable=False),
    sa.Column('Is_Active', sa.CHAR(length=1), nullable=False),
    sa.Column('Is_Deleted', sa.CHAR(length=1), nullable=False),
    sa.Column('Wallet_Balance', sa.Float(), nullable=False),
    sa.Column('Currency', sa.String(length=10), nullable=True),
    sa.Column('Last_Transaction_Id', sa.String(length=100), nullable=True),
    sa.Column('Payment_Mode', sa.String(length=50), nullable=True),
    sa.Column('Is_Wallet_Enabled', sa.Boolean(), nullable=False),
    sa.Column('Added_By', sa.Integer(), nullable=True),
    sa.Column('Added_On', sa.DateTime(), nullable=False),
    sa.Column('Modified_By', sa.Integer(), nullable=True),
    sa.Column('Modified_On', sa.DateTime(), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.Column('Deleted_On', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['User_Type_Id'], ['usertypes.User_Type_Id'], ),
    sa.PrimaryKeyConstraint('User_Id')
    )
    op.create_index(op.f('ix_users_Email'), 'users', ['Email'], unique=True)
    op.create_index(op.f('ix_users_Phone'), 'users', ['Phone'], unique=True)
    op.create_index(op.f('ix_users_User_Id'), 'users', ['User_Id'], unique=False)
    op.create_table('businessmanusers',
    sa.Column('Businessman_User_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_Id', sa.Integer(), nullable=False),
    sa.Column('User_Type_Id', sa.Integer(), nullable=False),
    sa.Column('Business_Type_Id', sa.Integer(), nullable=False),
    sa.Column('Brand_Name', sa.String(length=100), nullable=False),
    sa.Column('Business_Type_Name', sa.String(length=100), nullable=False),
    sa.Column('Is_Active', sa.CHAR(length=1), nullable=False),
    sa.Column('Business_Code', sa.String(length=100), nullable=True),
    sa.Column('Business_Status', sa.String(length=50), nullable=True),
    sa.Column('Bussiness_Logo', sa.String(length=500), nullable=True),
    sa.Column('Bussiness_Banner', sa.String(length=500), nullable=True),
    sa.Column('Bussiness_Description', sa.String(length=500), nullable=True),
    sa.Column('Added_By', sa.Integer(), nullable=True),
    sa.Column('Added_On', sa.DateTime(), nullable=False),
    sa.Column('Modified_By', sa.Integer(), nullable=True),
    sa.Column('Modified_On', sa.DateTime(), nullable=False),
    sa.Column('Is_Deleted', sa.CHAR(length=1), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.Column('Deleted_On', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Business_Type_Id'], ['businesstypes.Business_Type_Id'], ),
    sa.ForeignKeyConstraint(['User_Id'], ['users.User_Id'], ),
    sa.ForeignKeyConstraint(['User_Type_Id'], ['usertypes.User_Type_Id'], ),
    sa.PrimaryKeyConstraint('Businessman_User_Id')
    )
    op.create_index(op.f('ix_businessmanusers_Businessman_User_Id'), 'businessmanusers', ['Businessman_User_Id'], unique=False)
    op.create_table('locationuseraddress',
    sa.Column('User_Address_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_Id', sa.Integer(), nullable=False),
    sa.Column('Location_Id', sa.Integer(), nullable=False),
    sa.Column('Pincode_Id', sa.Integer(), nullable=False),
    sa.Column('Address_Line1', sa.String(length=255), nullable=False),
    sa.Column('Address_Line2', sa.String(length=255), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=False),
    sa.Column('Pincode', sa.String(length=10), nullable=False),
    sa.Column('Longitude', sa.String(length=20), nullable=False),
    sa.Column('Latitude', sa.String(length=20), nullable=False),
    sa.Column('Map_Location_Url', sa.String(length=255), nullable=True),
    sa.Column('Address_Type', sa.String(length=50), nullable=False),
    sa.Column('Is_Default', sa.CHAR(length=1), nullable=False),
    sa.Column('Is_Active', sa.CHAR(length=1), nullable=False),
    sa.Column('Added_By', sa.Integer(), nullable=True),
    sa.Column('Added_On', sa.DateTime(), nullable=False),
    sa.Column('Modified_By', sa.Integer(), nullable=True),
    sa.Column('Modified_On', sa.DateTime(), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.Column('Deleted_On', sa.DateTime(), nullable=True),
    sa.Column('Is_Deleted', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['Location_Id'], ['locationmaster.Location_Id'], ),
    sa.ForeignKeyConstraint(['Pincode_Id'], ['locationactivepincode.Pincode_Id'], ),
    sa.ForeignKeyConstraint(['User_Id'], ['users.User_Id'], ),
    sa.PrimaryKeyConstraint('User_Address_Id')
    )
    op.create_index(op.f('ix_locationuseraddress_Address_Line1'), 'locationuseraddress', ['Address_Line1'], unique=True)
    op.create_index(op.f('ix_locationuseraddress_User_Address_Id'), 'locationuseraddress', ['User_Address_Id'], unique=False)
    op.create_table('usersessions',
    sa.Column('Session_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_Id', sa.Integer(), nullable=False),
    sa.Column('Token', sa.String(length=255), nullable=False),
    sa.Column('Device_Info', sa.String(length=255), nullable=True),
    sa.Column('IP_Address', sa.String(length=45), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=True),
    sa.Column('Expires_At', sa.DateTime(), nullable=True),
    sa.Column('Login_Timestamp', sa.DateTime(), nullable=True),
    sa.Column('Logout_Timestamp', sa.DateTime(), nullable=True),
    sa.Column('Added_By', sa.Integer(), nullable=True),
    sa.Column('Added_On', sa.DateTime(), nullable=False),
    sa.Column('Modified_By', sa.Integer(), nullable=True),
    sa.Column('Modified_On', sa.DateTime(), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.Column('Deleted_On', sa.DateTime(), nullable=True),
    sa.Column('Is_Deleted', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['User_Id'], ['users.User_Id'], ),
    sa.PrimaryKeyConstraint('Session_Id'),
    sa.UniqueConstraint('Token')
    )
    op.create_index(op.f('ix_usersessions_Session_Id'), 'usersessions', ['Session_Id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersessions_Session_Id'), table_name='usersessions')
    op.drop_table('usersessions')
    op.drop_index(op.f('ix_locationuseraddress_User_Address_Id'), table_name='locationuseraddress')
    op.drop_index(op.f('ix_locationuseraddress_Address_Line1'), table_name='locationuseraddress')
    op.drop_table('locationuseraddress')
    op.drop_index(op.f('ix_businessmanusers_Businessman_User_Id'), table_name='businessmanusers')
    op.drop_table('businessmanusers')
    op.drop_index(op.f('ix_users_User_Id'), table_name='users')
    op.drop_index(op.f('ix_users_Phone'), table_name='users')
    op.drop_index(op.f('ix_users_Email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_userpermissions_User_Permission_Id'), table_name='userpermissions')
    op.drop_table('userpermissions')
    op.drop_index(op.f('ix_locationactivepincode_Pincode_Id'), table_name='locationactivepincode')
    op.drop_index(op.f('ix_locationactivepincode_Pincode'), table_name='locationactivepincode')
    op.drop_table('locationactivepincode')
    op.drop_index(op.f('ix_businesscategories_Business_Category_Id'), table_name='businesscategories')
    op.drop_table('businesscategories')
    op.drop_index(op.f('ix_usertypes_User_Type_Name'), table_name='usertypes')
    op.drop_index(op.f('ix_usertypes_User_Type_Id'), table_name='usertypes')
    op.drop_table('usertypes')
    op.drop_index(op.f('ix_pages_Page_Id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_locationmaster_Location_Name'), table_name='locationmaster')
    op.drop_index(op.f('ix_locationmaster_Location_Id'), table_name='locationmaster')
    op.drop_table('locationmaster')
    op.drop_index(op.f('ix_businesstypes_Business_Type_Name'), table_name='businesstypes')
    op.drop_index(op.f('ix_businesstypes_Business_Type_Id'), table_name='businesstypes')
    op.drop_table('businesstypes')
    # ### end Alembic commands ###
